# This is a basic workflow to help you get started with Actions

name: Search Wiki and generate markdown files

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Get properties from wiki and generate markdown files
        run: |
              python3 $GITHUB_WORKSPACE/.github/workflows/wiki_checklist_crawler.py \
              --url https://wiki.comakingspace.de \
              --meta checklist_title checklist_symbols checklist_link \
              --text Before checklist_before \
              --text During checklist_during \
              --text After checklist_after \
              --out markdown_files 
              
      - name: add, commit and push files to origin
        run: |
              git config --global user.name 'Wiki Checklist Crawler'
              git config --global user.email 'pakue95@users.noreply.github.com'
              git commit -am "Updated markdown files from wiki"
              git push
              
